title: Filippo Albertin Git Page
description: In estrema sintesi...
show_downloads: true
google_analytics:
remote_theme: pages-themes/merlot@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
